# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EnvoyMiniBuilder < Formula
  desc "Build Envoy on a remote Mac mini and publish GitHub release assets"
  homepage "https://github.com/dio/envoy-mini-builder"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dio/envoy-mini-builder/releases/download/v0.1.0/envoy-mini-builder_0.1.0_darwin_arm64.tar.gz"
      sha256 "2360cca96c95c3b4ffd8b6bc447b6f9f7f7c0e940c0ebc3d50d86b18df490b33"

      define_method(:install) do
        bin.install "envoy-mini-builder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dio/envoy-mini-builder/releases/download/v0.1.0/envoy-mini-builder_0.1.0_linux_amd64.tar.gz"
      sha256 "ab895642714508721cc0e2b298358568aa7af3534c4cf772fcab1780c0e855cd"
      define_method(:install) do
        bin.install "envoy-mini-builder"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dio/envoy-mini-builder/releases/download/v0.1.0/envoy-mini-builder_0.1.0_linux_arm64.tar.gz"
      sha256 "bd59c0c5b20c548ec65ae2ce4579024c50be2d70d8180b58e65b432e2cf0781f"
      define_method(:install) do
        bin.install "envoy-mini-builder"
      end
    end
  end

  test do
    system "#{bin}/envoy-mini-builder", "--version"
  end
end
