# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GatewayPairs < Formula
  desc "Deploy Envoy Gateway as isolated controller+dataplane pairs in a Kubernetes cluster"
  homepage "https://github.com/dio/gateway-pairs"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dio/gateway-pairs/releases/download/v0.2.0/gateway-pairs_0.2.0_darwin_amd64.tar.gz"
      sha256 "2d8ff7c9975387c255acd8f4d83c2eb623dca2a7cd3390a25dceeece4fe612e2"

      define_method(:install) do
        bin.install "gwp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dio/gateway-pairs/releases/download/v0.2.0/gateway-pairs_0.2.0_darwin_arm64.tar.gz"
      sha256 "4573006269208159c42cf477ede0422f56822ed7328cc027adfdc2526932d069"

      define_method(:install) do
        bin.install "gwp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dio/gateway-pairs/releases/download/v0.2.0/gateway-pairs_0.2.0_linux_amd64.tar.gz"
      sha256 "9694159e5e347df70304be7df24d5be56450f1e1bacadf875f202bf41eac0d4f"
      define_method(:install) do
        bin.install "gwp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dio/gateway-pairs/releases/download/v0.2.0/gateway-pairs_0.2.0_linux_arm64.tar.gz"
      sha256 "a6efd6f10c59c3d114f059ca0310bd9f1d5fe2f78a625ec27aba5f48be07b95b"
      define_method(:install) do
        bin.install "gwp"
      end
    end
  end

  test do
    system "#{bin}/gwp", "version"
  end
end
