# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GatewayPairs < Formula
  desc "Deploy Envoy Gateway as isolated controller+dataplane pairs in a Kubernetes cluster"
  homepage "https://github.com/dio/gateway-pairs"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dio/gateway-pairs/releases/download/v0.2.1/gateway-pairs_0.2.1_darwin_amd64.tar.gz"
      sha256 "82c7a91d588150b26ceb2408865122ad967b40ff2b4493d5967175dbad952428"

      define_method(:install) do
        bin.install "gwp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dio/gateway-pairs/releases/download/v0.2.1/gateway-pairs_0.2.1_darwin_arm64.tar.gz"
      sha256 "6bd6a4a0ddfefd8cdb05163f1ec73182385e59b0de3f77ab8af0ab3d33b693a8"

      define_method(:install) do
        bin.install "gwp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dio/gateway-pairs/releases/download/v0.2.1/gateway-pairs_0.2.1_linux_amd64.tar.gz"
      sha256 "ef1aa05e899d3c1dafaee15aff470d8520dee3557ff580d6faf1027d9a9bf7d1"
      define_method(:install) do
        bin.install "gwp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dio/gateway-pairs/releases/download/v0.2.1/gateway-pairs_0.2.1_linux_arm64.tar.gz"
      sha256 "14ad074f89325e8dad633b8c2a75e6d591535b3faba246f85c6d2a397fb35ea1"
      define_method(:install) do
        bin.install "gwp"
      end
    end
  end

  test do
    system "#{bin}/gwp", "version"
  end
end
