# This file was generated by GoReleaser. DO NOT EDIT.
cask "rute" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "828a6ab15dcc1a7dc88043930df1728c824e5f788d0a86aa24c48347b1f4f359"
      url "https://github.com/dio/rute/releases/download/v#{version}/rute_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5d11f6f28629be5c3fd598355076035953e6420b07e86e5651d03a1989cb6908"
      url "https://github.com/dio/rute/releases/download/v#{version}/rute_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c348d4567a07bac9b790ad4029baf381357a973736b673bea40e2eb9a91fa08c"
      url "https://github.com/dio/rute/releases/download/v#{version}/rute_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "05453eb78dbc5469d0be6053bb8335be1e8b1452bfe8a66245e3cdfa1a86415f"
      url "https://github.com/dio/rute/releases/download/v#{version}/rute_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rute"
  desc "Loopback OpenAI-compatible proxy backed by Codex OAuth"
  homepage "https://github.com/dio/rute"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rute"

  # No zap stanza required

end
