# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EnvoyMiniBuilder < Formula
  desc "Build Envoy on a remote Mac mini and publish GitHub release assets"
  homepage "https://github.com/dio/envoy-mini-builder"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dio/envoy-mini-builder/releases/download/v0.2.0/envoy-mini-builder_0.2.0_darwin_arm64.tar.gz"
      sha256 "df8545aaefa82374058cf2c46baf6f01cce375593989af66f7d884ec3108d28a"

      define_method(:install) do
        bin.install "envoy-mini-builder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dio/envoy-mini-builder/releases/download/v0.2.0/envoy-mini-builder_0.2.0_linux_amd64.tar.gz"
      sha256 "f868f1f74a305176ec8deb96fea0b07819667b1e585b1a82529697c749c97c54"
      define_method(:install) do
        bin.install "envoy-mini-builder"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dio/envoy-mini-builder/releases/download/v0.2.0/envoy-mini-builder_0.2.0_linux_arm64.tar.gz"
      sha256 "ab023a0dee2350cd3a670593e3692dafe5cb5bf7ae5298b215d66a2007008d53"
      define_method(:install) do
        bin.install "envoy-mini-builder"
      end
    end
  end

  test do
    system "#{bin}/envoy-mini-builder", "--version"
  end
end
