# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EnvoyMiniBuilder < Formula
  desc "Build Envoy on a remote Mac mini and publish GitHub release assets"
  homepage "https://github.com/dio/envoy-mini-builder"
  version "0.6.16"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dio/envoy-mini-builder/releases/download/v0.6.16/envoy-mini-builder_0.6.16_darwin_arm64.tar.gz"
      sha256 "68d06f1b17bc48baa5a07f990e1080ad74c6f1e4ec0c44a59355d4f7011ea230"

      define_method(:install) do
        bin.install "envoy-mini-builder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dio/envoy-mini-builder/releases/download/v0.6.16/envoy-mini-builder_0.6.16_linux_amd64.tar.gz"
      sha256 "a2929068dcc5ed7012390fd366daba73ab525652bd84e417f5040957d0c649b6"
      define_method(:install) do
        bin.install "envoy-mini-builder"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dio/envoy-mini-builder/releases/download/v0.6.16/envoy-mini-builder_0.6.16_linux_arm64.tar.gz"
      sha256 "6b746dfb8978d6bfebd5f23926c96cc57338688b96900698f32089048b476af5"
      define_method(:install) do
        bin.install "envoy-mini-builder"
      end
    end
  end

  test do
    system "#{bin}/envoy-mini-builder", "--version"
  end
end
