# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gwp < Formula
  desc "Deploy Envoy Gateway as isolated controller+dataplane pairs in a Kubernetes cluster"
  homepage "https://github.com/dio/gateway-pairs"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dio/gateway-pairs/releases/download/v0.1.1/gateway-pairs_0.1.1_darwin_amd64.tar.gz"
      sha256 "329689ac0e7835caedf7fb60c1bdd7d746ac76c7c03a5c9a265a4437ac994d49"

      define_method(:install) do
        bin.install "gwp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dio/gateway-pairs/releases/download/v0.1.1/gateway-pairs_0.1.1_darwin_arm64.tar.gz"
      sha256 "3c2cae818f790ef6e1ebffdf858f14e14420619f7f22e1b73acf1c0dcb139b0f"

      define_method(:install) do
        bin.install "gwp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dio/gateway-pairs/releases/download/v0.1.1/gateway-pairs_0.1.1_linux_amd64.tar.gz"
      sha256 "c8356727fd8e75d8e4080f69bf85a8a60ba5721b6fcc8ccb1f4dae828280e51a"
      define_method(:install) do
        bin.install "gwp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dio/gateway-pairs/releases/download/v0.1.1/gateway-pairs_0.1.1_linux_arm64.tar.gz"
      sha256 "0cfec9be25a085eda031e1c40c4a3e85f6e6581c3be76091e11fdce99c4924a4"
      define_method(:install) do
        bin.install "gwp"
      end
    end
  end

  test do
    system "#{bin}/gwp", "version"
  end
end
