# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rute < Formula
  desc "Loopback OpenAI-compatible proxy backed by Codex OAuth"
  homepage "https://github.com/dio/rute"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dio/rute/releases/download/v0.1.0/rute_0.1.0_darwin_amd64.tar.gz"
      sha256 "828a6ab15dcc1a7dc88043930df1728c824e5f788d0a86aa24c48347b1f4f359"

      define_method(:install) do
        bin.install "rute"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dio/rute/releases/download/v0.1.0/rute_0.1.0_darwin_arm64.tar.gz"
      sha256 "5d11f6f28629be5c3fd598355076035953e6420b07e86e5651d03a1989cb6908"

      define_method(:install) do
        bin.install "rute"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dio/rute/releases/download/v0.1.0/rute_0.1.0_linux_amd64.tar.gz"
      sha256 "c348d4567a07bac9b790ad4029baf381357a973736b673bea40e2eb9a91fa08c"
      define_method(:install) do
        bin.install "rute"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dio/rute/releases/download/v0.1.0/rute_0.1.0_linux_arm64.tar.gz"
      sha256 "05453eb78dbc5469d0be6053bb8335be1e8b1452bfe8a66245e3cdfa1a86415f"
      define_method(:install) do
        bin.install "rute"
      end
    end
  end

  test do
    system bin/"rute", "version"
  end
end
